[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
antithesis_sdk = "0.2"
anyhow = { version = "1.0" }
assert_matches = "1.5"
axum = "0.8"
axum-test = "17.0"
bindgen = { version = "0.71", default-features = false }
blake3 = "1.5"
bs58 = "0.5"
bytes = { version = "1.9" }
clap = "4.5"
config = { version = "0.15", features = ["toml"] }
criterion = { version = "0.5" }
culprit = { version = "0.3" }
either = { version = "1.13" }
env_logger = "0.11"
fjall = "2.5"
foldhash = { version = "0.1" }
futures = { version = "0.3" }
hashbrown = { version = "0.15" }
itertools = { version = "0.14" }
log = "0.4"
lsm-tree = "2.5"
measured = "0.0.22"
memmap2 = "0.9"
nix = "0.29"
object_store = "0.11"
prost = { version = "0.13" }
prost-types = "0.13"
rand = { version = "0.8" }
reqwest = { version = "0.12" }
rlimit = "0.10"
roaring = "0.10"
rusqlite = "0.32"
serde = { version = "1.0" }
serde_json = { version = "1.0" }
static_assertions = "1.1"
tempfile = "3.15"
thiserror = { version = "2.0" }
tokio = "1"
tokio-util = "0.7"
tower-http = "0.6"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
tracing-test = "0.2"
tryiter = "0.6"
url = { version = "2.5" }
zerocopy = "0.8"
