[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
antithesis_sdk = "0.2"
culprit = { version = "0.3" }
bytes = { version = "1.9" }
prost = { version = "0.13" }
anyhow = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
object_store = "0.11"
memmap2 = "0.9"
rlimit = "0.10"
nix = "0.29"
prost-types = "0.13"
axum = "0.8"
tower-http = "0.6"
itertools = { version = "0.14" }
reqwest = { version = "0.12" }
tokio = "1"
config = { version = "0.15", features = ["toml"] }
thiserror = { version = "2.0" }
futures = { version = "0.3" }
url = { version = "2.5" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
log = "0.4"
tempfile = "3.15"
zerocopy = "0.8"
tokio-util = "0.7"
tryiter = "0.5"
fjall = "2.5"
lsm-tree = "2.5"
env_logger = "0.11"
clap = "4.5"
bindgen = { version = "0.71", default-features = false }
measured = "0.0.22"
axum-test = "17.0"
tracing-test = "0.2"
rusqlite = "0.32"
either = { version = "1.13" }
criterion = { version = "0.5" }
roaring = "0.10"
bs58 = "0.5"
foldhash = { version = "0.1" }
hashbrown = { version = "0.15" }
rand = { version = "0.8" }
static_assertions = "1.1"
assert_matches = "1.5"
blake3 = "1.5"
