[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
circular-buffer = "1.0"
glob = "0.3"
anyhow = "1.0"
assert_matches = "1.5"
axum = "0.8"
axum-test = "17.2"
bindgen = { version = "0.71", default-features = false }
blake3 = "1.6"
bs58 = "0.5"
bytes = "1.10"
clap = "4.5"
config = { version = "0.15", features = ["toml"] }
criterion = "0.5"
crossbeam = "0.8"
culprit = "0.3"
linkme = "0.3"
either = "1.14"
event-listener = "5.4"
enum_dispatch = "0.3"
file-lock = "2.1"
fjall = { version = "2.6", features = ["bytes"] }
foldhash = "0.1"
futures = "0.3"
hashbrown = "0.15"
http = "1.2"
itertools = "0.14"
libloading = "0.8"
log = "0.4"
lsm-tree  = { version = "2.6", features = ["bytes"] }
measured = "0.0.22"
memmap2 = "0.9"
quote = "1.0"
syn = "2.0"
nix = "0.29"
object_store = "0.11"
parking_lot = "0.12"
prost = "0.13"
prost-types = "0.13"
proc-macro2 = "1.0"
rand = "0.9"
reqwest = "0.12"
rlimit = "0.10"
roaring = "0.10"
rusqlite = "0.33"
rustc_version_runtime = "0.3"
serde = "1.0"
serde_json = "1.0"
static_assertions = "1.1"
tempfile = "3.17"
thiserror = "2.0"
tokio = "1"
tokio-util = "0.7"
tower-http = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
tryiter = "0.6"
ureq = { version = "3.0", default-features = false, features = ["rustls", "brotli"]}
url = "2.5"
zerocopy = "0.8"

[workspace.lints.clippy]
disallowed_methods = "deny"
uninlined-format-args = "warn"
doc-markdown = "warn"
map-unwrap-or = "warn"
