[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
bytes = "1.8"
prost = "0.13"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
object_store = "0.11"
memmap2 = "0.9"
rlimit = "0.10"
nix = "0.29"
prost-types = "0.13"
axum = "0.7"
tower-http = "0.6"
itertools = "0.13"
reqwest = "0.12"
tokio = "1"
twelf = { version = "0.15", default-features = false }
thiserror = "2.0"
futures = "0.3"
url = "2.5"
serde = "1.0"
log = "0.4"
tempfile = "3.12"
zerocopy = "0.8"
tokio-util = "0.7"
tryiter = "0.3.0"
fjall = "2.4"
lsm-tree = "2.4"
env_logger = "0.11"
clap = "4.5"
bindgen = "0.71"
measured = "0.0.22"
axum-test = "16.2"
tracing-test = "0.2"
rusqlite = "0.32"
either = "1.13"
criterion = "0.5"
roaring = "0.10"
bs58 = "0.5"
foldhash = "0.1"
hashbrown = "0.15"
rand = "0.8"
static_assertions = "1.1"
