[package]
name = "splinter"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7"
either = "1.13.0"
static_assertions = "1"
thiserror = "1.0"
zerocopy = { version = "0.8", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
roaring = "0.10"

[[bench]]
name = "bitmaps"
harness = false
