[package]
name = "splinter"
version = "0.1.0"
edition = "2021"

[dependencies]
static_assertions = "1.1.0"
thiserror = "1.0.64"
zerocopy = { version = "0.8.1", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
roaring = "0.10"

[[bench]]
name = "bitmaps"
harness = false
