[package]
name = "splinter"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
static_assertions = "1.1.0"
thiserror = "1.0.64"
zerocopy = { version = "0.7.35", features = ["derive"] }
