catalog_update_concurrency = 128
download_concurrency = 128
write_concurrency = 128

[objectstore]
type = "s3_compatable"
bucket = "graft-primary"
prefix = "pagestore"

[metastore]
endpoint = "https://graft-metastore.fly.dev"
