[package]
name = "graft-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-core = { path = "../graft-core" }
splinter = { path = "../splinter" }

bytes = "1.8.0"
prost = "0.13.3"
prost-types = "0.13.3"
zerocopy = "0.8.9"
