[package]
name = "graft-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-core = { path = "../graft-core" }
splinter = { path = "../splinter" }

culprit = { workspace = true }
bytes = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
zerocopy = { workspace = true }
