[package]
name = "graft-core"
version = "0.1.0"
edition = "2021"

[dependencies]
splinter = { path = "../splinter" }

culprit = { workspace = true }
bs58 = { workspace = true }
bytes = { workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
zerocopy = { workspace = true }
assert_matches = { workspace = true }

[features]
default = []
testutil = []
