[package]
name = "graft-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
bytes = "1.7.1"
foldhash = "0.1.3"
hashbrown = "0.15"
rand = "0.8.5"
serde = "1.0.215"
static_assertions = "1.1.0"
thiserror = "2.0"
zerocopy = { version = "0.8", features = ["derive"] }

[features]
default = []
testutil = []

[dev-dependencies]
futures = "0.3.31"
