[package]
name = "graft-sqlite"
version = "0.1.0"
edition = "2024"
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
graft-core = { path = "../graft-core" }
graft-client = { path = "../graft-client" }
graft-tracing = { path = "../graft-tracing" }
graft-proto = { path = "../graft-proto" }
sqlite-plugin = { path = "../sqlite-plugin" }

tracing = { workspace = true }
culprit = { workspace = true }
thiserror = { workspace = true }
enum_dispatch = { workspace = true }
parking_lot = { workspace = true }
tryiter = { workspace = true }
bytes = { workspace = true }
