[package]
name = "graft-sqlite"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
name = "graft"
crate-type = ["cdylib"]

[dependencies]
graft-core = { path = "../graft-core" }
graft-client = { path = "../graft-client" }
graft-proto = { path = "../graft-proto" }
graft-tracing = { path = "../graft-tracing" }

tracing = { workspace = true }
culprit = { workspace = true }
thiserror = { workspace = true }
enum_dispatch = { workspace = true }
parking_lot = { workspace = true }
tryiter = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }

[dependencies.sqlite-plugin]
path = "../sqlite-plugin"
default-features = false
features = ["dynamic"]

[dev-dependencies.sqlite-plugin]
path = "../sqlite-plugin"
default-features = false
features = ["static"]
