[package]
name = "graft-client"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-core = { path = "../graft-core" }
graft-proto = { path = "../graft-proto" }
splinter = { path = "../splinter" }

antithesis_sdk = { workspace = true }
bytes = { workspace = true }
culprit = { workspace = true }
fjall = { workspace = true, features = ["bytes"] }
futures = { workspace = true }
log = { workspace = true }
lsm-tree = { workspace = true, features = ["bytes"] }
prost = { workspace = true }
reqwest = { workspace = true, features = ["brotli"] }
serde = { workspace = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tryiter = { workspace = true }
url = { workspace = true }
zerocopy = { workspace = true }

[dev-dependencies]
graft-core = { path = "../graft-core", features = ["testutil"] }
env_logger = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
