[package]
name = "graft-client"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-core = { path = "../graft-core" }
graft-proto = { path = "../graft-proto" }
splinter = { path = "../splinter" }

bytes = "1.8"
prost = "0.13"
prost-types = "0.13"
zerocopy = "0.8"
reqwest = { version = "0.12" }
tokio = { version = "1" }
thiserror = "2.0"
futures = "0.3.31"
url = { version = "2.5.3", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }

[dev-dependencies]
fjall = "2.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
tryiter = "0.2.0"
