[package]
name = "graft-server"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-core = { path = "../graft-core" }
graft-proto = { path = "../graft-proto" }
splinter = { path = "../splinter" }
tokio = { version = "1.40.0", features = ["full", "test-util"] }
odht = { git = "https://github.com/carlsverre/odht.git" }
static_assertions = "1.1.0"
zerocopy = { version = "0.8", features = ["derive"] }
anyhow = "1.0.89"
thiserror = "1.0.63"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
object_store = { version = "0.11.0", features = ["aws"] }
bytes = "1.7.2"
memmap2 = "0.9.5"
rlimit = "0.10.2"
nix = { version = "0.29.0", features = ["fs"] }
hashbrown = "0.15"
pin-project = "1.1.5"
futures = "0.3.30"
axum = { version = "0.7.7", features = ["ws", "http2"] }
prost = "0.13.3"
itertools = "0.13.0"
fjall = "2.1.1"
tempfile = "3.12.0"
foldhash = "0.1.3"
tokio-util = "0.7.12"

[dev-dependencies]
axum-test = "16.2.0"
graft-core = { path = "../graft-core", features = ["testutil"] }
tracing-test = "0.2.5"
