[package]
name = "graft-test"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-client = { path = "../graft-client", features = ["antithesis"]}
graft-server = { path = "../graft-server" }
graft-core = { path = "../graft-core", features = ["testutil"] }
graft-tracing = { path = "../graft-tracing" }
splinter = { path = "../splinter" }
precept = { path = "../precept", features = ["antithesis"] }

culprit = { workspace = true }
crossbeam = { workspace = true }
file-lock = { workspace = true }
url = { workspace = true }
ureq = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
config = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
bs58 = { workspace = true }
