[package]
name = "graft-test"
version = "0.1.0"
edition = "2021"

[dependencies]
graft-client = { path = "../graft-client", features = ["antithesis"]}
graft-server = { path = "../graft-server" }
graft-core = { path = "../graft-core", features = ["testutil"] }
splinter = { path = "../splinter" }

antithesis_sdk = { workspace = true }
culprit = { workspace = true }
url = { workspace = true }
tokio = { workspace = true, features = ["full"] }
env_logger = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
config = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
