name: Antithesis

on:
  push:
    branches: ["main"]
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │  ┌───────────── hour (0 - 23)
    #         │  │  ┌───────────── day of the month (1 - 31)
    #         │  │  │  ┌───────────── month (1 - 12 or JAN-DEC)
    #         │  │  │  │  ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │  │  │  │  │
    #         │  │  │  │  │
    #         │  │  │  │  │
    #         *  *  *  *  *
    - cron: " 0  7  *  *  *"
    # Run every day at 7:00 AM UTC = 12:00 AM PST

permissions:
  contents: read

jobs:
  antithesis:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Start Antithesis Tests
        run: just run antithesis-run 15
        env:
          ANTITHESIS_TENANT: ${{ secrets.ANTITHESIS_TENANT }}
          ANTITHESIS_USERNAME: ${{ secrets.ANTITHESIS_USERNAME }}
          ANTITHESIS_PASSWORD: ${{ secrets.ANTITHESIS_PASSWORD }}
